# Generated by Django 3.1.7 on 2021-03-12 21:24

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(default=django.utils.timezone.now)),
                ('time_in', models.TimeField(default=datetime.time(8, 0))),
                ('time_out', models.TimeField(default=datetime.time(16, 0))),
                ('hours_code', models.CharField(choices=[('FBP', 'FBP'), ('AMCO', 'AMCO')], max_length=4, validators=[django.core.validators.RegexValidator(message='Please choose either FBP or AMCO.', regex='^(FBP|AMCO)$')])),
                ('fbp_payroll', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Please insert a non-negative number.'), django.core.validators.MaxValueValidator(limit_value=9999999.99, message='Payroll must be under $10 million.')])),
                ('amco_payroll', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Please insert a non-negative number.'), django.core.validators.MaxValueValidator(limit_value=9999999.99, message='Payroll must be under $10 million.')])),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
