# Generated by Django 3.1.7 on 2021-03-12 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Please insert a valid location name.', regex='^[a-zA-Z0-9,\\. :-]+$')]),
        ),
    ]
