# Generated by Django 3.1.7 on 2021-03-16 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20210312_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
