# Generated by Django 3.1.7 on 2021-03-12 14:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('ssn', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number. (XXX-XXX-XXXX)', regex='^\\d{3}-\\d{2}-\\d{4}$')])),
                ('description', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Description must consist of only letters.', regex='^[a-zA-Z\\. ]+$')])),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number. (XXX-XXX-XXXX)', regex='^\\d{3}-\\d{3}-\\d{4}(-\\d{2,6})?$')])),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='Please enter a valid street address.', regex='^\\d{1,5} [a-zA-Z0-9\\. ]+$')])),
                ('city', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Please enter a valid city name.', regex='^[a-zA-Z\\. -]+$')])),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'District of Columbia'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=20)),
                ('zip_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid ZIP code.', regex='^\\d{5}-(\\d{4})?$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
