# Generated by Django 3.1.7 on 2021-03-16 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_created',
        ),
    ]
