# Generated by Django 3.1.7 on 2021-03-16 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
